#!/bin/bash

sleep 10

for i in {1..10}
do
    ifconfig eth0 | fgrep UP &> /dev/null
    if [ $? -eq 0 ]
    then
	/usr/bin/php /var/www/html/php/ph_sensor.php
	exit 0
    fi
    sleep 3
done

exit 1
